project:
  type: website
  output-dir: docs

website:
  title: "Final Protfolio"
  navbar:
    search: true
    left:
    - text: "Home"
      href: index.qmd
    - text: "Project 1"
      href: Project 1/scorecard_analysis.qmd
    - text: "Project 2"
      href: Project 2/WCA_analysis.qmd 
    - text: "Project 3"
      href: Project 3/mapping.qmd
    - text: "Leah Levensailor"
      href: about.qmd
    

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

